version: '3.5'
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: angularcontainer  # Container name
      build: ./project # Location of our Dockerfile
      volumes: # Volume binding
        - './project:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > #For first build, add: ng new app &&
        bash -c "cd app/ && ng serve --host 0.0.0.0 --port 4200"