# Generated by Django 3.1.3 on 2020-12-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('race', models.CharField(choices=[('demigod', 'Demi-God'), ('elf', 'Elf'), ('human', 'Human'), ('troll', 'Troll'), ('god', 'God'), ('demon', 'Demon')], max_length=50)),
                ('class_type', models.CharField(choices=[('bruiser', 'Bruiser'), ('mage', 'Mage'), ('archer', 'Archer'), ('bowman', 'Bowman')], max_length=50)),
                ('element', models.CharField(choices=[('bruiser', 'Bruiser'), ('mage', 'Mage'), ('archer', 'Archer'), ('bowman', 'Bowman')], max_length=50)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_app.world')),
            ],
        ),
    ]
