# Generated by Django 3.1.3 on 2020-12-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('population', models.IntegerField()),
                ('global_rating', models.IntegerField()),
                ('water_rating', models.IntegerField()),
                ('diamond_rating', models.IntegerField()),
                ('gold_rating', models.IntegerField()),
                ('silver_rating', models.IntegerField()),
                ('cooper_rating', models.IntegerField()),
            ],
        ),
    ]
